matcher:
  KDTreeMatcher:
    knn: 5
    maxDist: 2.0
    epsilon: 1

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio: 0.80
  - SurfaceNormalOutlierFilter:
     maxAngle: 0.42

errorMinimizer:
  PointToPlaneErrorMinimizer:

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 100
  - BoundTransformationChecker:
      maxRotationNorm: 1.
      maxTranslationNorm: 10.00

inspector:
  NullInspector

logger:
  FileLogger
