- BoundingBoxDataPointsFilter:
    xMin: -1.0
    xMax: 1.0
    yMin: -0.5
    yMax: 0.5
    zMin: -0.5
    zMax: 0.5
    removeInside: 1

## - OctreeGridDataPointsFilter:
##     maxSizeByNode: 0.3

## - SurfaceCovarianceDataPointsFilter:
##     knn: 100
##     epsilon: 1.33
##     keepDensities: 1

## - DecomposeCovarianceDataPointsFilter:
##     keepNormals: 1

- FixStepSamplingDataPointsFilter:
      startStep: 3

- SurfaceNormalDataPointsFilter:
      knn: 12
      epsilon: 1.33
      keepNormals: 1
      keepDensities: 1
      keepEigenValues: 1
      keepEigenVectors: 1
      sortEigen: 1

- MaxDensityDataPointsFilter:
      maxDensity: 100.0  #80

- SimpleSensorNoiseDataPointsFilter:
    sensorType: 0

- ObservationDirectionDataPointsFilter

- OrientNormalsDataPointsFilter:
      towardCenter: 1

