- SurfaceNormalDataPointsFilter:
      knn: 9
      epsilon: 1.33
      keepNormals: 1
      keepDensities: 1
      keepEigenValues: 1
      keepEigenVectors: 1
      sortEigen: 1

- SimpleSensorNoiseDataPointsFilter:
    sensorType: 0

- ObservationDirectionDataPointsFilter

- OrientNormalsDataPointsFilter:
      towardCenter: 1

